trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:

  - stage: 
    displayName: Selenium Testing
    jobs:
    - job: selenium_tests
      displayName: Run Selenium Tests
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'

        - script: |
            pip install selenium
          displayName: 'Install Selenium'
                
        - script: |
            pip install webdriver_manager
          displayName: 'Install webdriver_manager'
        
        - script: |
            python test.py
          displayName: 'Run Selenium Tests'


  
